### ISSUE TITLE
BaseStorage could not be found!

### ISSUE THREAD

**Issue by evanricard** [BrianPeek/AzureSDKs-Unity#2]
Hi Brian, 

I've downloaded the Storage SDK and I am dumbfounded as to why I am getting this error for each of the storage-type files. 

![image](https://user-images.githubusercontent.com/30779615/44762137-f0f33880-ab13-11e8-8f30-6b35d721c9be.png)

I've combed through both this repo and the Azure-UnitySamples repo looking for the missing file.

Any help would be appreciated, thanks!

**Comment by BrianPeek** [comment]
Hey Evan! There should be a "BaseStorage.cs" file that gets imported from the package that those 4 classes inherit from. Can you verify that script is in your project?

**Comment by evanricard** [comment]
Thanks for the quick response! I just double-checked to see what gets imported with the azure-storage-unity-8.6.0.unitypackage and I am not seeing it. The "Storage Bird" scripts do not contain a BaseStorage.cs file as well...I have checked everywhere (I think) and I'm not seeing it!

**Comment by BrianPeek** [comment]
Very strange, I'm seeing it here on import:

![image](https://user-images.githubusercontent.com/2321675/44762975-19c8fd00-ab17-11e8-8dd9-97d0ea93d0f1.png)

It should be in Assets\AzureSamples\Storage ...

**Comment by evanricard** [comment]
Strange indeed, I don't even get the AzureStorage.unity scene. The other two SDK's look just fine let me pull the storage sdk/package down again maybe that will solve something.

**Comment by evanricard** [comment]
![image](https://user-images.githubusercontent.com/30779615/44763168-e9ce2980-ab17-11e8-9cc0-c16262cc6c7b.png)

**Comment by evanricard** [comment]
![image](https://user-images.githubusercontent.com/30779615/44763203-1eda7c00-ab18-11e8-8b9c-53f7c330e935.png)

**Comment by BrianPeek** [comment]
I am so very, very confused. :)  What version of Unity?

**Comment by BrianPeek** [comment]
I just tried it in 2017.4.1f1 and it worked as well.  I don't even know what to suggest?!?!?

**Comment by BrianPeek** [comment]
Well, I do.  You could try grabbing the file itself from here and adding manually?

https://github.com/BrianPeek/AzureSDKs-Unity/blob/master/Storage/Assets/AzureSamples/Storage/BaseStorage.cs

**Comment by evanricard** [comment]
Ya I will do that, should fix my issue. Alas, I could not even find that file - or, so I thought - in the repo but now I realize I was looking in the other repo. The only thing I know is that it is time for bed lol. Goodnight and thanks again Brian!

**Comment by BrianPeek** [comment]
Sure thing, good luck!
