### ISSUE TITLE
AssetPackage broken assembly/duplicate assemblies

### ISSUE THREAD

**Issue by DrDecipher** [BrianPeek/AzureSDKs-Unity#5]
I'm trying to find a version of Unity that properly loads the asset package preoperly.

With versions of Unity 2018.2 - 2018.20 I am receiving the following:
Unloading broken assembly Assets/Plugins/Microsoft.Azure.EventHubs.dll, this assembly can cause crashes in the runtime

Loading the same package into  2018.6 I get:
error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\_Repos\DigitalTwin\Unity\Azure_2018_6\Assets\Plugins\Microsoft.CSharp.dll' and 'C:\Program Files\Unity_2018.3.6f1\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\Microsoft.CSharp.dll'. Remove one of the duplicate references.

In the latter removing either Microsoft.CSharp.dll breaks a variety of other things so I'm open to suggestions.

Thanks,
Tharyn

**Comment by BrianPeek** [comment]
Looks like you might be running this with full .NET framework?  These are only compatible with the new .NET Standard support.  Please see the details here and let me know if that works:

https://docs.microsoft.com/en-us/sandbox/gamedev/unity/azure-event-hubs-unity#import-the-sdk

**Comment by DrDecipher** [comment]
So in each case I have the Config set to match the link and have restarted Unity to ensure the settings have taken.
.NET 4.x Equivalent
IL2CPP
.NET Standard 2.0

I also tried 2018.1 and received these two:
Unloading broken assembly Assets/Plugins/Newtonsoft.Json.dll, this assembly can cause crashes in the runtime
Unloading broken assembly Assets/Plugins/Microsoft.Azure.EventHubs.dll, this assembly can cause crashes in the runtime


In each case, it is a clean install of Unity 2018.x and a new project. Any other suggestions?

Thank you again!

**Comment by BrianPeek** [comment]
Those errors may continue to show up.  Unity knows about it but I haven't seen a fix for that.  Try running in the editor and/or building your target, it *should* work.

**Comment by DrDecipher** [comment]
2018.1 and .2 seem to run. I'll dig in further tomorrow. The 2018.6 multiple .net dll error is fatal.

Cheers

**Comment by BrianPeek** [comment]
Hmmm.which version?  2018.6 isn't a Unity build...maybe 2018.x.6 where x == 1 2 or 3 ?

**Comment by DrDecipher** [comment]
Sorry that was a typo
Unity_2018.3.6f1

**Comment by BrianPeek** [comment]
Gotcha. Not sure what the problem would be in that version, it should just work.  I won't have time to review until after GDC next week but will take a look then.  Sorry!

**Comment by DrDecipher** [comment]
All good thank you for responding so quickly. If I get more information I'll post it.

**Comment by DrDecipher** [comment]
Brian,
I was able to get the project to work disregarding the errors with Unity 2018.2 x. Unity 2018.3.x still has a duplicate error issue that is fatal, but what I have learned in the last week is that this may be the wrong path for my objective regardless. 

I have a Pi3 registered as a device and posting data to IoT Central. I have not yet found a way to connect Unity on a PC to IoT Central to receive this data. It would seem that with the SDKs you have provided so far you might know the best path for me to explore.

Based on the documentation, IoT Hubs seems over kill for just a couple devices with limited data being exchanged. Do you have any thoughts?

Thanks,
Tharyn

**Comment by BrianPeek** [comment]
Hello!  Sorry for the delay...

I'm not sure I have a perfect answer for you.  Can you describe what problem you're having on the UWP side and what you're looking to do overall?  Feel free to email if it's easier to discuss, my firstname.lastname@microsoft.com Thanks!

Brian Peek (hint hint)  :)

**Comment by BrianPeek** [comment]
Chatted via email, workaround with Event Hubs, will look at duplicate assembly issue with 2018.3 when I find time.  Closing for now. Thanks!
