### ISSUE TITLE
Unity3D 2019.x , error 9d34608e

### ISSUE THREAD

**Issue by martdob** [BrianPeek/AzureSDKs-Unity#6]
Hi,
the issue occures if you do following:
1. open new fresh Unity3D 2019.1x project
2. import the AzureStorage unitypackage
3. following error occures:
Microsoft (R) Visual C# Compiler version 2.9.1.65535 (9d34608e)
Copyright (C) Microsoft Corporation. All rights reserved.

4. delete the folder "Plugin" which contains the DLLs
5. the error 9d34608e disapaers but the project can't work

**Comment by BrianPeek** [comment]
Unfortunately Unity changed their compiler in 2019.x and has rendered some of these packages unusable.  I don't have a perfect fix nor an ETA on when one might be available.  Sorry!

**Comment by martdob** [comment]
This SDK was so useful. It is pity to hear that there is no ETA or a fix for the future Unity releases. Thanks for supporting the community so far.

**Comment by MartinGebske** [comment]
Yeah. Encountered the same issues. With the EventHubs it's worse. Unity won't start the demo scene becuase of compile errors... which doesn't exist.

Would be great to see the SDK up and running again.

**Comment by ostritch** [comment]
@BrianPeek are there any plans to support the Azure SDK for Unity in 2019+ or should we find another solution? Thanks.

**Comment by BrianPeek** [comment]
@ostritch - I would suggest finding another solution. I do not have workarounds for the changes made in Unity to allow these SDKs to work 100%.

**Comment by ostritch** [comment]
Thanks @BrianPeek. That's a shame because it was a neat solution. It would be good to update the download pages to say it is no longer supported from 2019.X...

**Comment by BrianPeek** [comment]
Doc pages are edited and will be live shortly.  Closing this for now as there is no workaround...
