### ISSUE TITLE
FormatException: One of the identified items was in an invalid format. (Unity 2018.4.15f1)

### ISSUE THREAD

**Issue by gabrieltm9** [BrianPeek/AzureSDKs-Unity#7]
Trying desperately to table.DeleteIfExistsAsync, or just delete a table by any means. Throws this error: 

FormatException: One of the identified items was in an invalid format.
System.Net.Http.Headers.HttpHeaders.AddInternal (System.String name, System.Collections.Generic.IEnumerable`1[T] values, System.Net.Http.Headers.HeaderInfo headerInfo, System.Boolean ignoreInvalid) (at <960ab25595cb4b1cb8c4959d26375323>:0)
System.Net.Http.Headers.HttpHeaders.Add (System.String name, System.Collections.Generic.IEnumerable`1[T] values) (at <960ab25595cb4b1cb8c4959d26375323>:0)
System.Net.Http.Headers.HttpHeaders.Add (System.String name, System.String value) (at <960ab25595cb4b1cb8c4959d26375323>:0)
Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpRequestMessageFactory.BuildRequestForTableOperation[T] (Microsoft.WindowsAzure.Storage.Core.Executor.RESTCommand`1[T] cmd, System.Uri uri, Microsoft.WindowsAzure.Storage.Core.UriQueryBuilder builder, System.Nullable`1[T] timeout, Microsoft.WindowsAzure.Storage.Table.TableOperation operation, Microsoft.WindowsAzure.Storage.Table.CloudTableClient client, System.Net.Http.HttpContent content, Microsoft.WindowsAzure.Storage.OperationContext ctx, Microsoft.WindowsAzure.Storage.Table.TablePayloadFormat payloadFormat, Microsoft.WindowsAzure.Storage.Core.Auth.ICanonicalizer canonicalizer, Microsoft.WindowsAzure.Storage.Auth.StorageCredentials credentials) (at <46e7f1dd0a584a2bb6c0c731c7791320>:0)
Microsoft.WindowsAzure.Storage.Table.TableOperation+<>c__DisplayClass64_0.<DeleteImpl>b__0 (Microsoft.WindowsAzure.Storage.Core.Executor.RESTCommand`1[T] cmd, System.Uri uri, Microsoft.WindowsAzure.Storage.Core.UriQueryBuilder builder, System.Net.Http.HttpContent cnt, System.Nullable`1[T] serverTimeout, Microsoft.WindowsAzure.Storage.OperationContext ctx) (at <46e7f1dd0a584a2bb6c0c731c7791320>:0)
Microsoft.WindowsAzure.Storage.Core.Executor.Executor+<ExecuteAsyncInternal>d__4`1[T].MoveNext () (at <46e7f1dd0a584a2bb6c0c731c7791320>:0)
Rethrow as StorageException: One of the identified items was in an invalid format.
Microsoft.WindowsAzure.Storage.Core.Executor.Executor+<ExecuteAsyncInternal>d__4`1[T].MoveNext () (at <46e7f1dd0a584a2bb6c0c731c7791320>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Microsoft.WindowsAzure.Storage.Table.CloudTable+<DeleteIfExistsAsync>d__47.MoveNext () (at <46e7f1dd0a584a2bb6c0c731c7791320>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
WorkshopController+<Test>d__49.MoveNext () (at Assets/Scripts/Workshop/WorkshopController.cs:119)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:155)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:105)

Code:
CloudTableClient tableClient = StorageAccount.CreateCloudTableClient();
CloudTable table = tableClient.GetTableReference("Test2");
await table.DeleteIfExistsAsync();

**Comment by BrianPeek** [comment]
Based on https://github.com/Azure/azure-storage-net/issues/437 and https://github.com/mono/mono/pull/4058, it appears this is an incompatibility with the Storage SDK and Mono.  While it's fixed in the Mono branch, I would bet this fix is not in Unity's Mono branch.  Unfortunately I don't have a solution or workaround for the problem.  :(

**Comment by gabrieltm9** [comment]
That's alright, thanks for the great asset anyways. Can you think of any other way to delete these tables?

**Comment by BrianPeek** [comment]
One thought popped in my head:  perhaps you can call the REST endpoint directly?
- https://docs.microsoft.com/en-us/rest/api/storageservices/table-service-rest-api
- https://docs.microsoft.com/en-us/rest/api/storageservices/delete-table

**Comment by gabrieltm9** [comment]
I did try this, but was unsuccessful likely do to bad formatting of the web request. Ill give it another shot later
