### ISSUE TITLE
Issues with deploying onto HoloLens 2 - "The lazily initialized type does not have a public parameter constructor"

### ISSUE THREAD

**Issue by neoncraze** [BrianPeek/AzureSDKs-Unity#8]
Hi, I'm trying to fetch some telemetry data through the Event Hub. Developing on Unity 2019.1.14f with the latest SDK off the repo, I'm constantly getting this issue. 

I've implemented a Task dispatcher and ensuring that I'm making my function calls on the main thread. It seems to be that the issue comes from the call to EventHubClient.CreateReceiver(string consumerGroupName, string partitionId, DateTime startTime), and I'm not sure how I should proceed.

[AzureHubError.txt](https://github.com/BrianPeek/AzureSDKs-Unity/files/4131835/AzureHubError.txt)

**Comment by BrianPeek** [comment]
Unfortunately these SDKs aren't working properly with Unity 2019 due to changes they have made to the editor/player.  I do not have a fix.  Sorry!

**Comment by BrianPeek** [comment]
My one and only suggestion for you is to ensure you have the link.xml file in your project, which shoudl be included in the unitypackage you got here.  But, that may not be enough to fix the problem.

**Comment by neoncraze** [comment]
Appreciate the prompt response. My mistake for not paying attention to the Unity versions!
It is now, however, stuck awaiting for PartitionReceiver.ReceiveAsync. It works when running on the PC, but doesn't when deployed on the HoloLens 2. Is this an issue with threading, or should I be investigating somewhere else?

**Comment by BrianPeek** [comment]
Could be threading, could be the IL2CPP process mangling something.  Unfortunately I'm not certain where to look.  :(

**Comment by neoncraze** [comment]
Gotcha no worries, thanks for the follow up!
